### ISSUE TITLE
bug when log files does not exists (when running in a container)

### ISSUE THREAD

**Issue by gawel** [bearstech/jobq#1]
It just print some errors:
```
root@567d237b92f4:/home/user# jobq-profile -q dump
Use of uninitialized value $user in concatenation (.) or string at /usr/bin/jobq-profile line 60.
gzip: /var/log/user.log.gz: No such file or directory
Use of uninitialized value $user in concatenation (.) or string at /usr/bin/jobq-profile line 84.
No jobq event found for user '' and queue 'dump'
```

**Comment by zerodeux** [comment]
Fixed for the $user warning.

Can't be trivially fixed for the missing syslog's user.log, it relies on it. The idea was to 1/ log - obviously and 2/ to use the log as both a human and computer data source for diagnostics and statistics. Syslog is still the de facto standard since even systemd's journal has a syslog input and output interface.

As a no-trivial fix we could try to use a plain logfile if syslog is not there. Would that be useful, and for when ?

**Comment by gawel** [comment]
containers are used for testing only. I guess touching the file is acceptable for this use case. And jobq's main feature works as expected without it.
So if it's not trivial lets wontfix it
